---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: logger
          image: localhost:5000/logger
          command: 
            - bash
            - -c
            - |-
              while true; do
                echo `date`
              done
